### Add a name
POST http://localhost:8080/api/persons
Content-Type: application/json

{
    "firstName": "Miguel",
    "lastName": "Figueiredo"
}

### Gets the list of names
GET http://localhost:8080/api/persons