version: '3'

services:
  rabbitmq:
    container_name: 'rabbitmq'
    image: 'rabbitmq:3.11-management-alpine'
    ports:
      # The standard AMQP protocol port
      - '5672:5672'
      # HTTP management UI
      - '15672:15672'
