{
 "title": "Tasks",
 "description": "Spring Boot (Micrometer) with Executors.",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "namespace",
    "label": "Namespace",
    "query": {
     "query": "label_values(executor_active_threads, namespace)"
    }
   },
   {
    "name": "application",
    "label": "Application",
    "query": {
     "query": "label_values(executor_active_threads{namespace=\"$namespace\"}, application)"
    }
   },
   {
    "name": "instance",
    "label": "Instance",
    "query": {
     "query": "label_values(executor_active_threads{namespace=\"$namespace\", application=\"$application\"}, instance)"
    }
   },
   {
    "name": "executor_name",
    "label": "Executor",
    "query": {
     "query": "label_values(executor_active_threads{namespace=\"$namespace\",application=\"$application\", instance=~\"$instance\"}, name)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Active Threads",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(executor_active_threads{namespace=\"$namespace\", application=\"$application\", instance=~\"$instance\", name=~\"$executor_name\"}) by (namespace, application, name)",
     "legendFormat": "active threads"
    }
   ]
  },
  {
   "title": "Tasks",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(executor_queued_tasks{namespace=\"$namespace\", application=\"$application\", instance=~\"$instance\", name=~\"$executor_name\"}) by(namespace, application, name)",
     "legendFormat": "queued tasks"
    },
    {
     "expr": "sum(increase(executor_completed_tasks_total{namespace=\"$namespace\", application=\"$application\", instance=~\"$instance\", name=~\"$executor_name\"}[$__rate_interval])) by(namespace, application, name)",
     "legendFormat": "completed tasks"
    }
   ]
  },
  {
   "title": "hello tasks",
   "type": "timeseries",
   "description": "The approximate total number of tasks that have completed execution.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(rate(executor_task_hello_seconds_count{namespace=\"$namespace\", application=\"$application\", instance=~\"$instance\"}[$__rate_interval])) by(namespace, application, name)",
     "legendFormat": "number"
    },
    {
     "expr": "sum(rate(executor_task_hello_seconds_sum{namespace=\"$namespace\", application=\"$application\", instance=~\"$instance\"}[$__rate_interval])) by(namespace, application, name) / sum(rate(executor_task_hello_seconds_count{namespace=\"$namespace\", application=\"$application\", instance=~\"$instance\"}[$__rate_interval])) by(namespace, application, name)",
     "legendFormat": "average time"
    }
   ]
  },
  { "title": "Tasks", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 } }
 ]
}