version: '3'

services:
  sftp:
    container_name: 'sftp'
    image: 'atmoz/sftp'
    platform: 'linux/amd64'
    volumes:
      - ./users.conf:/etc/sftp/users.conf:ro
      - ./upload:/home/sftp/upload
    ports:
      - '2222:22'

  redis:
    container_name: redis
    image: 'redis'
    ports:
      - '6379:6379'
