version: '3'

services:
  postgres:
    container_name: 'postgres'
    image: 'postgres'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'

  app:
    container_name: 'app'
    image: 'docker.io/library/reactive-rest-and-jpa:0.0.1-SNAPSHOT'
    platform: 'linux/amd64'
    environment:
      - SPRING_R2DBC_URL=r2dbc:postgresql://postgres:5432/postgres
      - SPRING_FLYWAY_URL=jdbc:postgresql://postgres:5432/postgres
    ports:
      - '8080:8080'

  influxdb:
    image: influxdb:1.8
    container_name: influxdb
    hostname: influxdb
    ports:
      - "8086:8086"
    environment:
      - INFLUXDB_DB=k6

  grafana:
    image: grafana/grafana:9.0.4
    container_name: grafana
    hostname: grafana
    ports:
      - "3000:3000"
    environment:
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_BASIC_ENABLED=false
    volumes:
      - ./src/test/k6/grafana/provisioning/datasources:/etc/grafana/provisioning/datasources
      - ./src/test/k6/grafana/provisioning/dashboards:/etc/grafana/provisioning/dashboards
    depends_on:
      - influxdb
