services:
  postgres:
    container_name: 'postgres'
    image: 'postgres'
    hostname: 'postgres'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
    command:
      - -c
      - wal_level=logical
  redis:
    container_name: redis
    image: 'redis'
    ports:
      - '6379:6379'
