services:
  postgres:
    container_name: 'postgres'
    image: 'postgres'
    hostname: 'postgres'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
    command:
      - -c
      - wal_level=logical
    volumes:
      - ./etc/postgres/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
